name: Auto Tag

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and create tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Clone the repository
          git clone https://github.com/${{ github.repository }}.git .
          git fetch --tags
          
          # Get the latest tag, default to v0.0.0 if no tags exist
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          
          # Extract version number and increment patch version
          VERSION=${LATEST_TAG#v}
          IFS='.' read -ra ADDR <<< "$VERSION"
          MAJOR=${ADDR[0]:-0}
          MINOR=${ADDR[1]:-0}  
          PATCH=${ADDR[2]:-0}
          
          # Increment patch version
          PATCH=$((PATCH + 1))
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          
          echo "New version will be: $NEW_VERSION"
          
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create and push tag
          echo "Creating tag: $NEW_VERSION"
          git tag $NEW_VERSION
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $NEW_VERSION
          echo "Tag $NEW_VERSION created successfully!"